### ISSUE TITLE
Workers do not work

### ISSUE THREAD

**Issue by amgstone** [shammysha/homeassistant-binance-pool#10]
Error during setup of component binance_pool
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/binance_pool/init.py", line 78, in async_setup
await binance_data.async_update_mining()
File "/config/custom_components/binance_pool/init.py", line 260, in async_update_mining
workers_list = miner_list.get("workerDatas", [])
AttributeError: 'bool' object has no attribute 'get'

```
configuration.yaml
binance_pool:
  name: My Binance
  domain: com
  api_key: ...
  api_secret: ...
  native_currency:
    - UAH
  balances:
    - LTC
    - BTC
    - DOGE
  exchanges:
    - BTCUSD
  miners:
    - account
```

without: miners: - account, is work.
