### ISSUE TITLE
Amount from wallet

### ISSUE THREAD

**Issue by amgstone** [shammysha/homeassistant-binance-pool#17]
How to make a sum in usd out of a wallet fiat and spot and funding? [http://joxi.ru/5mdny8OS3GJW9A](url)

**Comment by shammysha** [comment]
You can make template sensor in your configuration.yaml
For example...

```
template:
  - sensor:
    - name: '**My Binance USDT total**'
      state: "{{ (states('**sensor.my_binance_usdt_balance**')|float + states('**sensor.my_binance_usdt_funding**')|float)|float }}"

```
Adjust intitities  in "state" definition fo Your sensors
